using System;
using System.Linq;
using System.Web.Services;
using BinaryOptionBL.Admin;
using BinaryOptionBO.Admin;
using System.Net.Mail;
using BinaryOptionBL.Common;

namespace BinaryOption.WebServices
{
    /// <summary>
    /// Summary description for ForgotPassword
    /// </summary>
    [WebService(Namespace = "http://tempuri.org/")]
    [WebServiceBinding(ConformsTo = WsiProfiles.BasicProfile1_1)]
    [System.ComponentModel.ToolboxItem(false)]
    // To allow this Web Service to be called from script, using ASP.NET AJAX, uncomment the following line. 
    [System.Web.Script.Services.ScriptService]
    public class ForgotPassword : System.Web.Services.WebService
    {
        [WebMethod]
        public string HelloWorld()
        {
            return "Hello World";
        }

        /// <summary>
        /// Created By : Satish Verma
        /// Created Date : 25-Nov-2014
        /// Purpose : To save regenerated password in encrypted password and send regarding email to that user
        /// </summary>
        /// <param name="email"></param>
        /// <returns></returns>
        [WebMethod]
        public string ForgetPassword(string email)
        {
            string strResult = string.Empty;
            ForgetPasswordBO objForgetPasswordBO = new ForgetPasswordBO();
            try
            {
                string password = string.Empty;
                objForgetPasswordBO.Email = email;
                objForgetPasswordBO.Password = PasswordGenerator();
                password = objForgetPasswordBO.Password;
                objForgetPasswordBO.EncrytedPassword = new MD5Secure().Encrypt(objForgetPasswordBO.Password);

                objForgetPasswordBO = new ForgetPasswordBL().ForgetPassword(objForgetPasswordBO);
                objForgetPasswordBO.Password = password;
                objForgetPasswordBO.Email = email;

                if (objForgetPasswordBO.Result == "1")
                {
                    SendMail(objForgetPasswordBO);
                    strResult = objForgetPasswordBO.Result;
                }

            }
            catch (Exception ex)
            {
                strResult = "5"; // Exception
            }
            return strResult;
        }     

        /// <summary>
        /// 8 digit password generator randomly
        /// </summary>
        /// <returns></returns>
        private string PasswordGenerator()
        {
            var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@#$%";
            var random = new Random();
            var result = new string(
                Enumerable.Repeat(chars, 8)
                          .Select(s => s[random.Next(s.Length)])
                          .ToArray());
            return result;
        }

        private string SendMail(ForgetPasswordBO objForgetPasswordBO)
        {
            string strResult = string.Empty;
            try
            {
                MailMessage email = new MailMessage();
                email.To.Add(new MailAddress(objForgetPasswordBO.Email));
                email.From = new MailAddress("lkumar@seasiainfotech.com");
                email.Subject = "Forgot Password";
                email.Body = "Hi, Your new password has been generated by system as follows:- <br /> Your User name is: " + objForgetPasswordBO.UserName + ".<br /> Your Password is: " + objForgetPasswordBO.Password + ".";
                email.IsBodyHtml = true;
                System.Net.Mail.SmtpClient smtpc = new System.Net.Mail.SmtpClient();
                smtpc.Host = ("10.8.18.41");
                smtpc.Port = 25;
                smtpc.UseDefaultCredentials = false;
                smtpc.EnableSsl = false;
                smtpc.Credentials = new System.Net.NetworkCredential("lkumar@seasiainfotech.com", "mind@123");
                //System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate(object s, System.Security.Cryptography.X509Certificates.X509Certificate certificate, System.Security.Cryptography.X509Certificates.X509Chain chain, System.Net.Security.SslPolicyErrors sslPolicyErrors) { return true; };
                smtpc.Send(email);
                strResult = "Sent";
            }
            catch (Exception ex)
            {
                strResult = "NotSent";
            }
            return strResult;
        }
    }
}
